import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import swaggerUi from 'swagger-ui-express';
import { config } from './config.js';
import { connectDatabase } from './db.js';
import { startMqtt } from './mqtt.js';
import { authRequired } from './middleware/auth.js';
import { errorHandler, notFound } from './middleware/error.js';
import swaggerDocument from './config/swagger.json' with { type: 'json' };
import authRoutes from './routes/auth.js';
import dashboardRoutes from './routes/dashboard.js';
import areaRoutes from './routes/area.js';
import sensorRoutes from './routes/sensor.js';
import deviceRoutes from './routes/device.js';
import thresholdRoutes from './routes/threshold.js';
import alertRoutes from './routes/alert.js';
import activityRoutes from './routes/activity.js';
import taskRoutes from './routes/task.js';
import userRoutes from './routes/user.js';

const app=express();
app.use(cors({origin:config.corsOrigin,credentials:true}));
app.use(express.json({limit:'1mb'}));
app.use(morgan('dev'));
app.get('/health',(req,res)=>res.json({status:'ok',service:'GREEN GARDEN API',dataMode:config.dataMode,mqtt:config.mqtt.enabled}));
app.use('/api',swaggerUi.serve,swaggerUi.setup(swaggerDocument));
app.use('/auth',authRoutes);
app.use('/dashboard',authRequired,dashboardRoutes);
app.use('/area',authRequired,areaRoutes);
app.use('/sensor',authRequired,sensorRoutes);
app.use('/device',authRequired,deviceRoutes);
app.use('/threshold',authRequired,thresholdRoutes);
app.use('/alert',authRequired,alertRoutes);
app.use('/activity',authRequired,activityRoutes);
app.use('/task',authRequired,taskRoutes);
app.use('/user',authRequired,userRoutes);
app.use(notFound);app.use(errorHandler);

await connectDatabase().catch((error)=>{console.error('[database]',error.message);process.exitCode=1;});
startMqtt();
app.listen(config.port,()=>console.log(`GREEN GARDEN API: http://localhost:${config.port} | Swagger: /api`));
