import { Router } from 'express';
import { store, nextId } from '../data/store.js';
import { allowRoles } from '../middleware/auth.js';
const router=Router();
const publicUser=(u)=>({id:u.user_id,user_id:u.user_id,full_name:u.full_name,email:u.email,status:u.status,role:store.roles.find(r=>r.role_id===u.role_id)?.role_name});
router.get('/profile',(req,res)=>{const u=store.users.find(x=>x.user_id===req.user.id);res.json(publicUser(u));});
router.get('/',allowRoles('admin'),(req,res)=>res.json(store.users.map(publicUser)));
router.post('/',allowRoles('admin'),(req,res)=>{const role=store.roles.find(r=>r.role_name===req.body.role);const item={user_id:nextId(store.users,'user_id'),role_id:role?.role_id||2,full_name:req.body.full_name,email:req.body.email,password_hash:`plain:${req.body.password||'demo123'}`,status:req.body.status||'active'};if(store.users.some(x=>x.email===item.email))return res.status(409).json({message:'Email đã tồn tại'});store.users.push(item);res.status(201).json(publicUser(item));});
router.put('/:id',allowRoles('admin'),(req,res)=>{const item=store.users.find(x=>x.user_id===Number(req.params.id));if(!item)return res.status(404).json({message:'Không tìm thấy người dùng'});if(req.body.role){const role=store.roles.find(r=>r.role_name===req.body.role);if(role)item.role_id=role.role_id;}Object.assign(item,{full_name:req.body.full_name??item.full_name,email:req.body.email??item.email,status:req.body.status??item.status});res.json(publicUser(item));});
router.post('/:id/toggle',allowRoles('admin'),(req,res)=>{const item=store.users.find(x=>x.user_id===Number(req.params.id));if(!item)return res.status(404).json({message:'Không tìm thấy người dùng'});item.status=item.status==='active'?'locked':'active';res.json(publicUser(item));});
export default router;
